### PR TITLE
Replace Rollup with Esbuild.

### PR DESCRIPTION
**Pull request by Bonkles**
This was, i think, the fastest build upgrade ever suggested by mortal man. 

@bhousel check it! 

image

There certainly are quite a few differences in the target built dist/iD.js file, but it seems to work well enough on both the latest chrome and safari instances. 

The build is AMAZINGLY fast. Like, too-good-to-be-true fast.

### CODE REVIEW

**Comment by bhousel** [comment]
> The build is AMAZINGLY fast. Like, too-good-to-be-true fast.

Awesome job @Bonkles!  Yes has been my experience using esbuild with other projects too - 2 orders of magnitude faster than rollup is normal. ✨ 

We can probably remove rollup + plugins, and find an esbuild-based way to create the legacy bundle (esbuild + esbuild_plugin_babel) so the tests will still work.

**Comment by Bonkles** [comment]
Got it- I'll work on getting the legacy builds emitted with esbuild and see if I can get the tests to work.

**Comment by bhousel** [comment]
@Bonkles I've updated all the companion projects in 19552fc08, so NSI might be ok now?  I'm interested to see whether this helps esbuild and Babel import the json data.

**Comment by Bonkles** [comment]
Fixed up the legacy build to also use esbuild- it seems to emit javascript for older browsers successfully, as the `npm test` target ran successfully: 

image

**Comment by Bonkles** [comment]
Just added the ability to visualize the dev build with `npm run esbuild:dev` && `npm run esbuild:visualize`. This creates a 'stats.html' file in the root that can be opened in a browser, which shows a treeview: 

image

**Pull request merged**
