### PR TITLE
Mapillary v4

### PR DESCRIPTION
**Pull request by nickplesha**
Hi!

This PR updates the Mapillary integration to use the new API (v4). Documentation is here: https://www.mapillary.com/developer/api-documentation/

Changes:
- Uses latest vector tiles for images, sequences, traffic signs and map features
- Uses latest API for image detections
- Uses latest Mapillary JS
- Removes a bunch of obsolete code
- Simplifies the state in the Mapillary service
- Fixes unit tests 
- Fixes a bunch of bugs

Let me know if you have any questions or feedback.

### CODE REVIEW

**Review by Bonkles — COMMENTED** [review]
Looks good at first glance, Let me enable the build to fire and I will deploy a test version of this code up on the site, and we can tire-kick live.

**Review by Bonkles — APPROVED** [review]

**Comment by Bonkles** [comment]
test deploy is live at: https://mapwith.ai/rapid/f7402013a-dist/index.html

I have rebuilt the translations using `npm run translate` but it still seems there are a bunch of issues.

**Comment by nickplesha** [comment]
I noticed the translation errors when the map feature layer is on. It comes from the map feature "title" which is not displayed anywhere so I removed it.

**Review by Bonkles — CHANGES_REQUESTED** [review]
It seems as though there are a few issues with strings being referenced that simply aren't there. Example: 

`Missing en translation: mapillary_map_features.marking.discrete.arrow.left
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.marking.discrete.arrow.straight
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.construction.barrier.temporary
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.marking.discrete.other_marking
Missing en translation: mapillary_map_features.object.water_valve
Missing en translation: mapillary_map_features.object.water_valve
Missing en translation: mapillary_map_features.marking.discrete.arrow.right
Missing en translation: mapillary_map_features.marking.discrete.arrow.split_right_or_straight
Missing en translation: mapillary_map_features.marking.discrete.arrow.left
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.water_valve
Missing en translation: mapillary_map_features.marking.discrete.other_marking
Missing en translation: mapillary_map_features.marking.discrete.arrow.straight
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.marking.discrete.arrow.straight
Missing en translation: mapillary_map_features.object.water_valve
Missing en translation: mapillary_map_features.object.water_valve
Missing en translation: mapillary_map_features.marking.discrete.arrow.straight
Missing en translation: mapillary_map_features.construction.flat.driveway
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.marking.discrete.other_marking
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.marking.discrete.other_marking
Missing en translation: mapillary_map_features.construction.flat.driveway
Missing en translation: mapillary_map_features.object.water_valve
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.parking_meter
Missing en translation: mapillary_map_features.marking.discrete.other_marking
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.construction.flat.driveway
Missing en translation: mapillary_map_features.construction.flat.driveway
Missing en translation: mapillary_map_features.object.parking_meter
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.marking.discrete.symbol.bicycle
Missing en translation: mapillary_map_features.object.parking_meter
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.marking.discrete.arrow.straight
Missing en translation: mapillary_map_features.marking.discrete.arrow.straight
Missing en translation: mapillary_map_features.marking.discrete.arrow.left
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.object.parking_meter
Missing en translation: mapillary_map_features.marking.discrete.other_marking
Missing en translation: mapillary_map_features.marking.discrete.arrow.straight
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.parking_meter
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.water_valve
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.construction.flat.driveway
Missing en translation: mapillary_map_features.construction.flat.driveway
Missing en translation: mapillary_map_features.construction.flat.driveway
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.marking.discrete.symbol.bicycle
Missing en translation: mapillary_map_features.object.junction_box
Missing en translation: mapillary_map_features.marking.discrete.other_marking
Missing en translation: mapillary_map_features.construction.flat.driveway
Missing en translation: mapillary_map_features.marking.discrete.symbol.bicycle
Missing en translation: mapillary_map_features.object.parking_meter
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.object.parking_meter
Missing en translation: mapillary_map_features.marking.discrete.arrow.straight
Missing en translation: mapillary_map_features.marking.discrete.arrow.straight
Missing en translation: mapillary_map_features.object.water_valve
Missing en translation: mapillary_map_features.marking.discrete.arrow.split_left_or_straight
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.construction.flat.driveway
Missing en translation: mapillary_map_features.marking.discrete.text
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.object.parking_meter
Missing en translation: mapillary_map_features.construction.flat.driveway
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.marking.discrete.stop_line
Missing en translation: mapillary_map_features.object.parking_meter
Missing en translation: mapillary_map_features.construction.flat.driveway
`

**Review by Bonkles — APPROVED** [review]

**Pull request merged**
