### PR TITLE
Add background imagery label to footer.

### PR DESCRIPTION
**Pull request by Bonkles**
Super simple- this is a feature request by QA to add the imagery label to the footer of the page. This is now more necessary since we have improved hotkeys for imagery switching. 

Label appears in the lower-left, in RapiD Pink. 

image

### CODE REVIEW

**Review by vanreece — APPROVED** [review]
download (1)

**Comment by bhousel** [comment]
I think we already don't do a great job of showing all the necessary attributions.  They are all over the place - different locations, fonts, colors, and languages.  So I'd prefer to see a bit more design cohesion in how we present information like this.

If we absolutely must ship this feature quickly, then ok, but I think it's worth taking a design pass to see whether we can declutter all these texts.

95359399-18db2b80-0898-11eb-98be-9c0ae5757787

**Comment by Bonkles** [comment]
Agreed! In order, from left to right: 
1) Terms & conditions for that specific imagery (changes as you cycle)
2) The name of the Imagery currently being displayed (i.e. what just got added in This PR)
3) Our licensing for using RapiD/Map With AI
4) The 'Terms & Feedback' for mapbox. THIS SHOULDN'T BE HERE. I have no idea why this is displaying- it looks like some sort of vestigial problem that is also present in our current v3 Code.  Suspect that this link is there because it happens to be the same that should appear in item 1) when a mapbox satellite layer is displayed. 

So we need to get rid of #4, and perhaps add an imagery icon to better hint to the user what the imagery label is supposed to be. What do you think?

**Comment by bhousel** [comment]
> Agreed! In order, from left to right:

Sorry I probably wrote that comment too quickly.  Yes, you and I know what these things are. "What is all this stuff," is what a typical user would think.  It doesn't improve their mapping experience.

(btw, #4 mapbox terms appears because the locator overlay is displayed because it's <z16)

**Comment by Bonkles** [comment]
No no, I knew you knew what it meant. :) Just treating this like the public forum it is- other folks without context wouldn't have a clue what these things are! 

Here's what I propose- let's get this merged into v3 internal for our mappers. Then we can get some Design work from Nick, update the UI if necessary, and then port the functionality into our v2 branch while @vanreece works out the kinks of how to integrate with upstream iD.

**Pull request merged**
